services:
  - type: web
    name: matchingflobot
    runtime: python
    buildCommand: ""
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: TOKEN
        fromDashboard: true
      - key: WEBHOOK_URL
        fromDashboard: true
    plan: free
    autoDeploy: true
